---
- hosts: all
  vars_files:
    - default.config.yml

  # Using pre_tasks to make sure tasks run first
  pre_tasks:
    - import_tasks: tasks/build-setup.yml
    - import_tasks: tasks/font-setup.yml
    - import_tasks: tasks/go-setup.yml
    - import_tasks: tasks/brave-setup.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/lsp-setup.yml
    - import_tasks: tasks/tools-setup.yml
    - import_tasks: tasks/terminal-setup.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/gsettings-setup.yml

  # after everything is installed from the task we bring in our configurations
  # these live in a seperate role
  roles:
    - role: mariuskimmina.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
