---
- hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: mariuskimmina.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    import-tasks: tasks/go-setup.yml
