- name: required libraries for brave
  become: true
  apt:
    name: ["curl", "apt-transport-https"]

- name: Brave Browser apt key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    state: present

- name: Brave Browser apt installation
  become: true
  apt:
    update_cache: yes
    name: brave-browser
