---
- name: Check if go is already installed
  ansible.builtin.stat:
    path: "{{ go_dir }}"
  register: go_installed

- name: Remove go if it was already present
  ansible.builtin.file:
    path: "{{ go_dir}}"
    state: absent
  when: go_installed

- name: Download go
  ansible.builtin.get_url:
    url: "{{ go_url }}"
    dest: /tmp/go.tar.gz
    mode: '0777'

- name: Ensure go tarball is present
  ansible.builtin.file:
    path: /tmp/go.tar.gz
    state: file
  register: go_downloaded

- name: Install go
  become: yes
  ansible.builtin.unarchive:
    src: /tmp/go.tar.gz
    dest: "{{ go_dest }}"
    remote_src: yes
  when: go_downloaded
