- name: Alacritty PPA
  become: true
  apt_repository:
    validate_certs: no
    repo: 'ppa:aslatter/ppa'
    state: present

- name: Install alacritty
  become: true
  apt:
    name: alacritty
    state: present
