- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  become: true
  apt_repository:
   repo: ppa:kdenlive/kdenlive-stable
   state: present
   update_cache: True

- name: Install tools from apt (tmux, wireshark, fzf .....)
  become: true
  apt:
    name: ["tmux", "wireshark", "fzf", "kdenlive", "gimp", "xclip", "tldr", "ripgrep", "gnome-tweaks"]
